apiVersion: v1
kind: Pod
metadata:
  name: debug-shell
spec:
  containers:
  - name: debug
    image: python:3.10-slim
    command: [ "sleep", "3600" ]
    volumeMounts:
      - name: data
        mountPath: /app/data
      - name: certs
        mountPath: /app/certs
      - name: configs
        mountPath: /app/configs
  volumes:
    - name: data
      hostPath:
        path: /Users/sailor_omkar/Codes/SDP_implementation/data
    - name: certs
      hostPath:
        path: /Users/sailor_omkar/Codes/SDP_implementation/certs
    - name: configs
      hostPath:
        path: /Users/sailor_omkar/Codes/SDP_implementation/configs

