FROM python:3.10-slim

# Install openssl for runtime cert generation
RUN apt-get update && apt-get install -y openssl iptables && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy gateway code and cert generator
COPY src/gateway.py ./gateway.py
COPY src/generate_cert.py ./generate_cert.py
COPY src/entrypoint.sh ./entrypoint.sh


RUN pip install --no-cache-dir flask requests cryptography urllib3

# Ensure entrypoint script is executable
RUN chmod +x /app/entrypoint.sh

EXPOSE 5005/udp
EXPOSE 6000/udp

# Entrypoint: generates cert for pod IP, then starts gateway
ENTRYPOINT ["/app/entrypoint.sh"]
