FROM python:3.10-slim

WORKDIR /app

# Copy client code
COPY src/client.py .

# Install Python dependencies
RUN pip install --no-cache-dir requests cryptography urllib3

# Run client
CMD ["python3", "client.py"]
