# client yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdp-client
  template:
    metadata:
      labels:
        app: sdp-client
    spec:
      containers:
      - name: client
        image: sdp-client:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: client-data
          mountPath: /app/data
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        # No TLS mounts needed for verify=False
        resources:
          requests:
            cpu: "0.5"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
      volumes:
      - name: client-data
        emptyDir: {}
      restartPolicy: Always
